name: RustCI

on:
  pull_request:
  push:
    branches:
      - master

env:
  RUST_BACKTRACE: 1

jobs:
  test:
    name: Test Rust ${{ matrix.rust }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - { rust: stable,           os: ubuntu-latest }
          - { rust: beta,             os: ubuntu-latest }
          - { rust: nightly,          os: ubuntu-latest }
    steps:
      - uses: actions/checkout@v2
      - uses: hecrj/setup-rust-action@v1
        with:
          rust-version: ${{ matrix.rust }}
      - run: sudo apt-get install libpcap-dev
      - run: cargo test --verbose --workspace
      - run: cargo test --verbose --workspace --all-features
      - run: cargo test --verbose --workspace --no-default-features

  #Clippy
  clippy_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: rustup component add clippy
      - run: sudo apt-get install libpcap-dev
      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features

  # cargo-spellcheck
  cargo-spellcheck:
    name: Verify Code Formatting and Lint
    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: -Dwarnings
    steps:
      - uses: actions/checkout@v2
      - uses: hecrj/setup-rust-action@v1
      - run: sudo apt-get install libpcap-dev
      - run: cargo install cargo-spellcheck
      - run: cargo spellcheck -m 255 #Fail the CI if there are spelling mistakes

  # Cargo-audit, cargo-crev (Security reports and trust circles for crates), cargo-outdated (checks for out of date crates)
  security:
    name: Verify Crate and Dependency Security
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: hecrj/setup-rust-action@v1
      - uses: actions-rs/audit-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - run: sudo apt-get install libpcap-dev
      - run: cargo install cargo-outdated
      - run: cargo outdated
      
  # cargo-geiger (Checks for unsafe), rustig (Checks for panic! paths)
  reliability: 
    name: Check Crate and Dependency Reliability
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: hecrj/setup-rust-action@v1
      - run: sudo apt-get install libpcap-dev
      - run: sudo apt-get install libssl-dev
      - run: echo workingdir $(pwd)
      - run: cargo install cargo-geiger --git https://github.com/rust-secure-code/cargo-geiger.git --features vendored-openssl
      - run: cargo install rustig --git https://github.com/Technolution/rustig.git
      - run: cargo build
      - run: cd ecli && cargo geiger
      - run: cd eframework && cargo geiger
      - run: cd pcap_parser && cargo geiger
      - run: rustig --binary target/debug/ecli --full-crate-analysis --verbose